# Generated by Django 6.0.6 on 2026-06-17 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_account_member_role_profile"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramPhase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=20, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("hint", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "program_phase",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                (
                    "checkin_policy",
                    models.CharField(
                        choices=[
                            ("staff_scan", "Staff Scan"),
                            ("free_play", "Free Play"),
                        ],
                        default="staff_scan",
                        max_length=20,
                    ),
                ),
                (
                    "capacity_mode",
                    models.CharField(
                        choices=[("unlimited", "Unlimited"), ("limited", "Limited")],
                        default="unlimited",
                        max_length=20,
                    ),
                ),
                ("max_concurrent_teams", models.IntegerField(blank=True, null=True)),
                ("submission_config", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "station",
                "ordering": ["sub_event", "order"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "system_setting",
            },
        ),
        migrations.RemoveField(
            model_name="account",
            name="team_oid",
        ),
        migrations.AddField(
            model_name="account",
            name="google_sub",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("participant", "Participant"),
                    ("collab", "Collaborator"),
                    ("admin", "Admin"),
                ],
                default="participant",
                max_length=12,
            ),
        ),
        migrations.CreateModel(
            name="DiscordBroadcast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                (
                    "target",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("approved", "Approved"),
                            ("pending", "Pending"),
                            ("team_ids", "Specific Teams"),
                        ],
                        default="all",
                        max_length=10,
                    ),
                ),
                ("target_payload", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="broadcasts",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "discord_broadcast",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mssv", models.CharField(max_length=20, unique=True)),
                ("full_name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("faculty", models.CharField(blank=True, max_length=255, null=True)),
                ("school", models.CharField(blank=True, max_length=255, null=True)),
                ("facebook", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "discord_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="participant_profile",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "participant",
            },
        ),
        migrations.CreateModel(
            name="SubEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workflow", "Workflow"),
                            ("social", "Social"),
                            ("station_run", "Station Run"),
                            ("quiz", "Quiz"),
                            ("submission", "Submission"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("uses_stations", models.BooleanField(default=False)),
                ("note", models.TextField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_events",
                        to="api.programphase",
                    ),
                ),
            ],
            options={
                "db_table": "sub_event",
                "ordering": ["phase", "order"],
            },
        ),
        migrations.CreateModel(
            name="StationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("closed", "Closed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("entered_at", models.DateTimeField()),
                ("exited_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.IntegerField(default=0)),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_sessions",
                        to="api.account",
                    ),
                ),
                (
                    "exited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="exited_sessions",
                        to="api.account",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_sessions",
                        to="api.programphase",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="api.station",
                    ),
                ),
                (
                    "sub_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_sessions",
                        to="api.subevent",
                    ),
                ),
            ],
            options={
                "db_table": "station_session",
            },
        ),
        migrations.AddField(
            model_name="station",
            name="sub_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stations",
                to="api.subevent",
            ),
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="e.g. T0001", max_length=10, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "approval_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("approval_note", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "qr_token",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                (
                    "provision_state",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=10,
                    ),
                ),
                ("provision_last_error", models.TextField(blank=True, null=True)),
                ("provision_retry_count", models.IntegerField(default=0)),
                ("last_provisioned_at", models.DateTimeField(blank=True, null=True)),
                ("discord_role_id", models.BigIntegerField(blank=True, null=True)),
                ("text_channel_id", models.BigIntegerField(blank=True, null=True)),
                ("voice_channel_id", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_teams",
                        to="api.account",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_teams",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "team",
            },
        ),
        migrations.CreateModel(
            name="StationSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("attachment_payload", models.JSONField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("graded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="graded_submissions",
                        to="api.account",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="api.station",
                    ),
                ),
                (
                    "station_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="api.stationsession",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_submissions",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "station_submission",
            },
        ),
        migrations.AddField(
            model_name="stationsession",
            name="team",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_sessions",
                to="api.team",
            ),
        ),
        migrations.CreateModel(
            name="ScoreEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("station", "Station"),
                            ("bonus", "Bonus"),
                            ("penalty", "Penalty"),
                            ("manual", "Manual"),
                        ],
                        max_length=10,
                    ),
                ),
                ("points", models.IntegerField()),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_score_entries",
                        to="api.account",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entries",
                        to="api.programphase",
                    ),
                ),
                (
                    "station_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="score_entries",
                        to="api.stationsession",
                    ),
                ),
                (
                    "sub_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entries",
                        to="api.subevent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_entries",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "score_entry",
            },
        ),
        migrations.CreateModel(
            name="PhaseRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        choices=[
                            ("approved", "Approved"),
                            ("qualified", "Qualified"),
                            ("wildcard", "Wildcard"),
                            ("manual", "Manual"),
                        ],
                        default="approved",
                        max_length=20,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roster",
                        to="api.programphase",
                    ),
                ),
                (
                    "qualified_from_phase",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="promoted_to",
                        to="api.programphase",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phase_rosters",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "phase_roster",
            },
        ),
        migrations.CreateModel(
            name="EventCheckIn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("reverted", "Reverted")],
                        default="active",
                        max_length=10,
                    ),
                ),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("meta", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scanner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scanned_checkins",
                        to="api.account",
                    ),
                ),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_checkins",
                        to="api.programphase",
                    ),
                ),
                (
                    "sub_event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_checkins",
                        to="api.subevent",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_checkins",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "event_checkin",
            },
        ),
        migrations.CreateModel(
            name="TeamMembership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_captain", models.BooleanField(default=False)),
                ("team_number", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "participant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.participant",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_membership",
            },
        ),
        migrations.CreateModel(
            name="AdvancementRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode",
                    models.CharField(
                        choices=[("top_n", "Top N"), ("manual", "Manual")],
                        default="top_n",
                        max_length=10,
                    ),
                ),
                ("slots", models.IntegerField(default=0)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="published_advancements",
                        to="api.account",
                    ),
                ),
                (
                    "from_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advancement_from",
                        to="api.programphase",
                    ),
                ),
                (
                    "to_phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="advancement_to",
                        to="api.programphase",
                    ),
                ),
            ],
            options={
                "db_table": "advancement_rule",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("from_phase", "to_phase"), name="uq_advancement_from_to"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="station",
            constraint=models.UniqueConstraint(
                fields=("sub_event", "code"), name="uq_station_event_code"
            ),
        ),
        migrations.AddConstraint(
            model_name="stationsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("station", "team"),
                name="uq_active_session_station_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationsession",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("sub_event", "team"),
                name="uq_active_session_event_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="phaseroster",
            constraint=models.UniqueConstraint(
                fields=("phase", "team"), name="uq_roster_phase_team"
            ),
        ),
        migrations.AddConstraint(
            model_name="eventcheckin",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("sub_event", "team"),
                name="uq_active_checkin_event_team",
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("team", "participant"), name="uq_membership_team_participant"
            ),
        ),
        migrations.AddConstraint(
            model_name="teammembership",
            constraint=models.UniqueConstraint(
                fields=("participant",), name="uq_membership_participant"
            ),
        ),
    ]
