# Generated by Django 5.2.15 on 2026-06-21 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_programphase_station_systemsetting_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="avatar",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="faculty",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="account",
            name="school",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="MssvLinkAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mssv", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("linked", "Linked"),
                            ("overwritten", "Overwritten"),
                            ("blocked", "Blocked"),
                        ],
                        max_length=12,
                    ),
                ),
                ("old_email", models.EmailField(blank=True, max_length=255, null=True)),
                ("new_email", models.EmailField(blank=True, max_length=255, null=True)),
                ("discord_notified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_audits",
                        to="api.account",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_audits",
                        to="api.participant",
                    ),
                ),
                (
                    "prev_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="link_audits_displaced",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "mssv_link_audit",
                "ordering": ["-created_at"],
            },
        ),
    ]
