# Generated by Django 5.2.15 on 2026-06-21 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_account_avatar_account_faculty_account_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participant",
            name="cccd",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="participant",
            name="extra",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="payment_proof",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
