# Generated by Django 5.2.15 on 2026-06-21 00:39

from django.db import migrations


def seed_schema(apps, schema_editor):
    SystemSetting = apps.get_model("api", "SystemSetting")
    # Import the default schema lazily so we don't depend on model imports here.
    from api.services.registration_service import default_schema, SCHEMA_KEY
    SystemSetting.objects.get_or_create(
        key=SCHEMA_KEY, defaults={"value": default_schema()},
    )


def unseed_schema(apps, schema_editor):
    SystemSetting = apps.get_model("api", "SystemSetting")
    from api.services.registration_service import SCHEMA_KEY
    SystemSetting.objects.filter(key=SCHEMA_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_participant_cccd_participant_date_of_birth_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_schema, unseed_schema),
    ]
