# Generated by Django 5.2.15 on 2026-06-21 01:05

from django.db import migrations


def update_schema(apps, schema_editor):
    SystemSetting = apps.get_model("api", "SystemSetting")
    from api.services.registration_service import default_schema, SCHEMA_KEY
    new_value = default_schema()
    obj = SystemSetting.objects.filter(key=SCHEMA_KEY).first()
    if obj:
        # No admin UI yet, so it's safe to refresh the seeded schema in place.
        obj.value = new_value
        obj.save(update_fields=["value", "updated_at"])
    else:
        SystemSetting.objects.create(key=SCHEMA_KEY, value=new_value)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0008_seed_registration_schema"),
    ]

    operations = [
        migrations.RunPython(update_schema, noop),
    ]
