# Generated by Django 5.2.15 on 2026-06-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_stationassignment"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stationassignment",
            constraint=models.UniqueConstraint(
                fields=("collab", "station"), name="uq_assignment_collab_station"
            ),
        ),
    ]
