# Generated by Django 5.2.15 on 2026-07-10 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_late_registration_and_form_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="stationsubmission",
            name="is_correct",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
