# Generated by Django 5.2.15 on 2026-07-10 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_stationsubmission_is_correct"),
    ]

    operations = [
        migrations.AddField(
            model_name="scoreentry",
            name="submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="score_entries",
                to="api.stationsubmission",
            ),
        ),
        migrations.AddField(
            model_name="stationsubmission",
            name="score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
