# Generated by Django 5.2.15 on 2026-08-03 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0018_auditlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFormVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_ids", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_form_variants",
                        to="api.station",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_variants",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_form_variant",
                "unique_together": {("team", "station")},
            },
        ),
    ]
