# Generated by Django 5.2.15 on 2026-08-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_teamformvariant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="role",
            field=models.CharField(
                choices=[
                    ("participant", "Participant"),
                    ("collab", "Collaborator"),
                    ("admin", "Admin"),
                    ("master_admin", "Master Admin"),
                ],
                default="participant",
                max_length=20,
            ),
        ),
    ]
