# Generated by Django 5.2.15 on 2026-08-03 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_promote_seed_master_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="CaptainVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "candidate",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captain_votes_received",
                        to="api.participant",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captain_votes",
                        to="api.team",
                    ),
                ),
                (
                    "voter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="captain_votes_cast",
                        to="api.participant",
                    ),
                ),
            ],
            options={
                "db_table": "captain_vote",
                "unique_together": {("team", "voter")},
            },
        ),
    ]
