# Generated by Django 5.2.15 on 2026-08-10 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_invalidate_known_seed_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subevent",
            name="type",
            field=models.CharField(
                choices=[
                    ("workflow", "Workflow"),
                    ("social", "Social"),
                    ("station_run", "Station Run"),
                    ("quiz", "Quiz"),
                    ("submission", "Submission"),
                    ("survey", "Survey"),
                    ("custom", "Custom"),
                ],
                default="custom",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="TeamFormDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("response_payload", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_form_drafts",
                        to="api.station",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_drafts",
                        to="api.team",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_form_drafts",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "team_form_draft",
                "unique_together": {("team", "station")},
            },
        ),
    ]
