# Generated by Django 5.2.15 on 2026-08-11 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_participant_discord_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="pass_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="station",
            name="pass_threshold",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="station",
            name="scoring_mode",
            field=models.CharField(
                choices=[
                    ("pass_fail", "Đạt/Không đạt"),
                    ("threshold", "Ngưỡng điểm đạt"),
                    ("score_only", "Chỉ nhập điểm"),
                ],
                default="score_only",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="stationsession",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("pending", "Chưa chấm"),
                    ("passed", "Đạt"),
                    ("failed", "Không đạt"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subevent",
            name="replay_after_all",
            field=models.BooleanField(default=False),
        ),
    ]
