# Generated by Django 5.2.15 on 2026-08-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0026_participant_discord_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="payment_code",
            field=models.CharField(max_length=6, null=True, blank=True),
        ),
        migrations.AddField(
            model_name="team",
            name="payment_proof_file",
            field=models.JSONField(null=True, blank=True),
        ),
    ]
