# Generated by Django 5.2.15 on 2026-08-12 00:00

from django.db import migrations

PAYMENT_CONFIG_KEY = "payment_config"


def default_payment_config():
    return {
        "bank_bin": "970436",
        "bank_short_name": "Vietcombank",
        "account_no": "",
        "account_name": "",
        "fee_per_person": 25000,
        "prefix": "VNUTOUR2026",
        "template": "compact2",
    }


def seed_payment_config(apps, schema_editor):
    SystemSetting = apps.get_model("api", "SystemSetting")
    SystemSetting.objects.get_or_create(
        key=PAYMENT_CONFIG_KEY, defaults={"value": default_payment_config()},
    )


def unseed_payment_config(apps, schema_editor):
    SystemSetting = apps.get_model("api", "SystemSetting")
    SystemSetting.objects.filter(key=PAYMENT_CONFIG_KEY).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_team_payment_code_and_proof_file"),
    ]

    operations = [
        migrations.RunPython(seed_payment_config, unseed_payment_config),
    ]
