# Generated by Django 5.2.15 on 2026-08-12 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0027_station_scoring_mode_and_replay"),
        ("api", "0029_seed_payment_config"),
    ]

    operations = []
