# Generated by Django 5.2.15 on 2026-08-13 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0030_merge_20260812_1901"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhotoFrame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("image", models.JSONField(blank=True, default=dict)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.IntegerField(default=0)),
                ("download_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_frames",
                        to="api.account",
                    ),
                ),
            ],
            options={
                "db_table": "photo_frame",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FrameDownloadLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "frame_title",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("ip", models.CharField(blank=True, default="", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frame_downloads",
                        to="api.account",
                    ),
                ),
                (
                    "frame",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="downloads",
                        to="api.photoframe",
                    ),
                ),
            ],
            options={
                "db_table": "frame_download_log",
                "ordering": ["-created_at"],
            },
        ),
    ]
