# Generated by Django 5.2.15 on 2026-08-28 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_team_payment_confirmed_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamFormSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                (
                    "started_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.account",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_form_sessions",
                        to="api.station",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="form_sessions",
                        to="api.team",
                    ),
                ),
            ],
            options={
                "db_table": "team_form_session",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("team", "station"), name="uq_team_form_session_station"
                    )
                ],
            },
        ),
    ]
