# Generated by Django (simulated)

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_teamformsession'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.IntegerField(blank=True, null=True)),
                ('points', models.IntegerField(default=1)),
                ('order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_bank', to='api.subevent')),
            ],
            options={
                'db_table': 'question_bank_item',
                'ordering': ['sub_event', 'order', 'id'],
            },
        ),
    ]
