# Generated by Django 5.2.15 on 2026-08-31 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_questionbankitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionbankitem",
            name="correct_text",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="questionbankitem",
            name="type",
            field=models.CharField(default="quiz", max_length=20),
        ),
    ]
