# Generated by Antigravity

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_questionbankitem_correct_text_questionbankitem_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoframe",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
