# Generated by Django 5.2.15 on 2026-09-05 18:42

import django.db.models.functions.text
from django.db import migrations, models
from django.db.models import Count
from django.db.models.functions import Lower, Trim, Upper


def normalize_identity_fields(apps, schema_editor):
    """Normalize identifiers only when doing so cannot merge distinct rows."""
    Account = apps.get_model("api", "Account")
    Participant = apps.get_model("api", "Participant")
    Team = apps.get_model("api", "Team")

    def collision_count(model, field, normalizer, *, keep_blank=False):
        rows = model.objects.annotate(normalized=normalizer(Trim(field)))
        if not keep_blank:
            rows = rows.exclude(normalized__isnull=True).exclude(normalized="")
        return (
            rows.values("normalized")
            .annotate(row_count=Count("id"))
            .filter(row_count__gt=1)
            .count()
        )

    conflicts = {
        "account_email": collision_count(Account, "email", Lower, keep_blank=True),
        "account_mssv": collision_count(Account, "mssv", Upper),
        "participant_email": collision_count(Participant, "email", Lower),
        "participant_mssv": collision_count(Participant, "mssv", Upper),
        "team_owner": (
            Team.objects.exclude(owner_account_id__isnull=True)
            .values("owner_account_id")
            .annotate(row_count=Count("id"))
            .filter(row_count__gt=1)
            .count()
        ),
    }
    conflicts = {key: count for key, count in conflicts.items() if count}
    if conflicts:
        details = ", ".join(f"{key}={count}" for key, count in conflicts.items())
        raise RuntimeError(
            "Cannot enforce registration identity constraints until duplicate "
            f"records are resolved ({details})."
        )

    Account.objects.update(email=Lower(Trim("email")))
    Account.objects.exclude(mssv__isnull=True).update(mssv=Upper(Trim("mssv")))
    Participant.objects.update(email=Lower(Trim("email")))
    Participant.objects.update(mssv=Upper(Trim("mssv")))


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0041_feedpost_feedimage_feedreaction_feedcomment"),
    ]

    operations = [
        migrations.RunPython(normalize_identity_fields, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                name="uq_account_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="account",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("mssv"),
                condition=models.Q(
                    ("mssv__isnull", False), models.Q(("mssv", ""), _negated=True)
                ),
                name="uq_account_mssv_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Upper("mssv"),
                name="uq_participant_mssv_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("email"),
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                name="uq_participant_email_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="team",
            constraint=models.UniqueConstraint(
                condition=models.Q(("owner_account__isnull", False)),
                fields=("owner_account",),
                name="uq_team_owner_account",
            ),
        ),
    ]
