# Generated by Django 5.2.15 on 2026-09-13 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_fix_schemeless_feed_image_urls"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedcomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="api.feedcomment",
            ),
        ),
    ]
