# Generated by Django 5.2.15 on 2026-09-15 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_station_max_attempts"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventcheckin",
            name="checked_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="checked_out_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scanned_checkouts",
                to="api.account",
            ),
        ),
        migrations.AddField(
            model_name="eventcheckin",
            name="checkout_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="checkouts",
                to="api.station",
            ),
        ),
        migrations.AddField(
            model_name="station",
            name="kind",
            field=models.CharField(
                choices=[
                    ("play", "Trạm chơi"),
                    ("checkin", "Trạm check-in"),
                    ("checkout", "Trạm checkout"),
                ],
                default="play",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="subevent",
            name="replay_after_pass",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subevent",
            name="require_checkin",
            field=models.BooleanField(default=False),
        ),
    ]
