# Generated by Django 5.2.17 on 2026-09-21 20:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_stationsubmission_item_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyFormSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "survey_form_session",
            },
        ),
        migrations.AddField(
            model_name="stationsubmission",
            name="participant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="survey_submissions",
                to="api.participant",
            ),
        ),
        migrations.AddConstraint(
            model_name="stationsubmission",
            constraint=models.UniqueConstraint(
                fields=("station", "participant"), name="uq_survey_station_participant"
            ),
        ),
        migrations.AddField(
            model_name="surveyformsession",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.participant"
            ),
        ),
        migrations.AddField(
            model_name="surveyformsession",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.station"
            ),
        ),
        migrations.AddConstraint(
            model_name="surveyformsession",
            constraint=models.UniqueConstraint(
                fields=("station", "participant"), name="uq_survey_session_participant"
            ),
        ),
    ]
