# Generated by Django 5.2.15 on 2026-09-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_surveyformsession_stationsubmission_participant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="show_score_to_participants",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="stationsession",
            name="challenge_scores",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stationsession",
            name="form_score",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
