# Generated by Django 5.2.15 on 2026-09-26 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_station_challenges_and_score_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="max_stay_minutes",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stationsession",
            name="challenge_skips",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stationsession",
            name="penalty_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
