# Generated by Django 5.2.15 on 2026-09-22 14:18

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


def create_vector_extension(apps, schema_editor):
    """Install pgvector only on PostgreSQL; SQLite remains a test fallback."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


def keep_vector_extension(apps, schema_editor):
    # Reversing the app's tables leaves the extension installed in the
    # dedicated gallery database; dropping it gains nothing.
    pass


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.RunPython(create_vector_extension, keep_vector_extension),
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("hidden", "Hidden"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("folder_id", models.CharField(max_length=200)),
                ("resource_key", models.CharField(blank=True, max_length=200)),
                ("drive_folder_url", models.URLField(max_length=1000)),
                (
                    "import_status",
                    models.CharField(
                        choices=[
                            ("idle", "Idle"),
                            ("queued", "Queued"),
                            ("scanning", "Scanning"),
                            ("complete", "Complete"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("import_error", models.CharField(blank=True, max_length=80)),
                ("scan_id", models.UUIDField(default=uuid.uuid4)),
                ("page_token", models.TextField(blank=True)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SearchResult",
            fields=[
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("photo_ids", models.JSONField(default=list)),
                ("truncated", models.BooleanField(default=False)),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("drive_file_id", models.CharField(max_length=200)),
                ("resource_key", models.CharField(blank=True, max_length=200)),
                ("source_revision", models.CharField(max_length=200)),
                ("source_checksum", models.CharField(blank=True, max_length=128)),
                ("filename", models.CharField(max_length=500)),
                ("share_url", models.URLField(blank=True, max_length=2000)),
                ("download_url", models.URLField(blank=True, max_length=2000)),
                ("source_size", models.PositiveBigIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("error", models.CharField(blank=True, max_length=80)),
                ("indexing_error", models.CharField(blank=True, max_length=80)),
                ("seen_scan_id", models.UUIDField(null=True)),
                ("width", models.PositiveIntegerField(default=0)),
                ("height", models.PositiveIntegerField(default=0)),
                ("face_count", models.PositiveIntegerField(default=0)),
                ("model_version", models.CharField(blank=True, max_length=120)),
                ("thumbnail_key", models.CharField(blank=True, max_length=500)),
                ("preview_key", models.CharField(blank=True, max_length=500)),
                ("lease_token", models.UUIDField(null=True)),
                ("lease_until", models.DateTimeField(null=True)),
                ("attempts", models.PositiveIntegerField(default=0)),
                ("next_attempt", models.DateTimeField(null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="photo_gallery.album",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MediaObject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=500, unique=True)),
                ("active", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_objects",
                        to="photo_gallery.photo",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Face",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ordinal", models.PositiveIntegerField()),
                ("bbox", models.JSONField()),
                ("embedding", pgvector.django.vector.VectorField(dimensions=128)),
                ("model_version", models.CharField(db_index=True, max_length=120)),
                (
                    "photo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faces",
                        to="photo_gallery.photo",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="photo",
            constraint=models.UniqueConstraint(
                fields=("album", "drive_file_id"), name="photo_unique_source"
            ),
        ),
        migrations.AddConstraint(
            model_name="face",
            constraint=models.UniqueConstraint(
                fields=("photo", "ordinal"), name="photo_unique_face"
            ),
        ),
    ]
