# Generated by Django 5.2.15 on 2026-09-22 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_gallery", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediaobject",
            name="photo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="media_objects",
                to="photo_gallery.photo",
            ),
        ),
    ]
