# Generated by Django 5.2.15 on 2026-09-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo_gallery", "0002_alter_mediaobject_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="scan_folder_index",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="album",
            name="scan_folders",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="photo",
            name="folder_id",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
